FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /ibon-poc

# copy csproj and restore as distinct layers
COPY ibon-poc/*.csproj ./
RUN dotnet restore

# copy everything else and build app
COPY ibon-poc/. ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /ibon-poc
COPY --from=build /ibon-poc/out ./
#RUN rm -f Configs/appsettings.* && rm -f Secrets/secret.json

EXPOSE 5000

ENTRYPOINT ["dotnet", "ibon-poc.dll"]