FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /grpc

# copy csproj and restore as distinct layers
COPY GrpcGreeter/*.csproj ./
RUN dotnet restore

# copy everything else and build app
COPY GrpcGreeter/. ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /grpc
COPY --from=build /grpc/out ./

EXPOSE 5001

ENTRYPOINT ["dotnet", "GrpcGreeter.dll"]