FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY ibon-poc/*.csproj ./ibon-poc/
RUN dotnet restore

# copy everything else and build app
COPY ibon-poc/. ./ibon-poc/
WORKDIR /app/ibon-poc
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /ibon-poc
COPY --from=build /app/ibon-poc/out ./
RUN rm -f appsettings.* && rm -f secret.json
ENTRYPOINT ["dotnet", "ibon-poc.dll"]