apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc
  labels:
    account: grpc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc
  name: grpc-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc
      version: v1
  template:
    metadata:
      labels:
        app: grpc
        version: v1
    spec:
      serviceAccountName: grpc
      containers:
      - image: testcrr.azurecr.io/grpc:v1.0
        name: grpc
        ports:
          - containerPort: 5001
            name: grpc-web
