apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc
    service: grpc
  name: grpc
spec:
  ports:
  - name: grpc-web
    port: 5001
    targetPort: 5001
  selector:
    app: grpc
  type: ClusterIP
